### ISSUE TITLE
Fix clear_flapping method in Zino1EventManager

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/zinolib#48]
[BUG]: Typo in if-check `if event.type == Event.Type.PortState:`. `PortState` type doesnt exist, should be `PORTSTATE`.

Other desirable changes (nice-to-haves):

- clear_flapping should accept `event_id` instead of `event` (just like other event modification methods in Zino1EventManager)
- clear_flapping should return an updated event instead of `bool` (just like other event modification methods in Zino1EventManager)

**Comment by hmpf** [comment]
>     * clear_flapping should accept `event_id` instead of `event` (just like other event modification methods in Zino1EventManager)

`clear_flapping` takes an event because not any id will do though so they typing is wrong (and cannot be made corrcet for some definitions of correct.)

**Comment by hmpf** [comment]
>     * clear_flapping should return an updated event instead of `bool` (just like other event modification methods in Zino1EventManager)

I'm guessing clear_flapping returns a bool in the original because it is a signal sent to the router in question (please attempt to clear the flapping!), and the flapping may or may not actually have been cleared. The function returns with True iff the server accepted the signal, not when the event itself has changed.

@lunkwill42, in the old and  new servers, how much time would it take between `clear_flapping` is sent until we know whether it works?

**Comment by hmpf** [comment]
`clear_flapping` ought to have been directly on the PortStateEvent and not on the manager, just like `get_downtime`. The reason it is not is because `clear_flapping` needs to talk to the server while  `get_downtime` does not. For ease of testing, anything that do need to talk to the server is in the Manager.

I haven't managed to think of an elegant way to avoid the import loop.
