### ISSUE TITLE
Implement poll method in Zino1EventManager

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/zinolib#49]
IRL discussions we mentioned that polling feature is same as just manually fetching an event. But upon closer inspection of `poll()` method in `ritz` I see that there is a differentiation between _poll interface_ and _poll router_:

```py
        if self.type == caseType.PORTSTATE:
            return self._zino.poll_interface(
                self._attrs["router"], self._attrs["ifindex"]
            )
        else:
            return self._zino.poll_router(self._attrs["router"])
```

So a simple event refresh/fetch does not translate directly to `poll()` and so a separate method should be implemented in Zino1EventManager.

**Comment by hmpf** [comment]
What should a refresh do that is different from `poll`? If you look at the docstrings of `poll_router` and `poll_interface` methods you will see that this *is* how you ask for new data, there's just two different ways to do it and even the ritz-library hides that fact.  Same as with clear_flapping, we signal that we want new data but do not get it automatically.

**Comment by hmpf** [comment]
`create_event_from_id()` is just fetching attributes via `zinolib.ritz.ritz.get_raw_attributes`, no poll involved.

Even if `create_event_from_id()` were to run `poll()`, poll always just returns True if succeeding, otherwise an exception is raised. There is a delay from polling until new data *may* be available. Using `create_event_from_id()` is a "refresh" as in "get whatever's currently on the server", but poll is asking the *server* to refresh itself. First poll, then wait, then maybe `create_event_from_id()` will get new data.

The easiest way might be if by hitting the "poll"-button, first a `poll()` is done, then the `create_event_from_id()` is run in the background after a delay, if that is easily possible with HTMX.

When howitz uses ntie this won't be a problem because after filling the initial list of events, changes to the contents of the list only happens if ntie says so.
